version: 2
jobs:
  terraform-validate:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            terraform init
            terraform validate
  terraform-plan:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Validate
          command: |
            terraform init
            terraform plan
  terraform-apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            terraform init
            terraform apply -auto-approve
      - persist_to_workspace:
          root: /root
          paths:
            - project
  run-inspec-tests:
    docker:
      - image: docker.mirror.hashicorp.services/chef/inspec:latest
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Inspec Tests
          command: |
            inspec --version
      - persist_to_workspace:
          root: /root
          paths:
            - project
  terraform-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Terraform Destroy
          command: |
            terraform destroy -auto-approve
workflows:
  version: 2
  infrastructure-tests:
    jobs:
      - terraform-validate
      - terraform-plan:
          requires:
            - terraform-validate
      - terraform-apply:
          requires:
            - terraform-plan
      - run-inspec-tests:
          requires:
            - terraform-apply
      - terraform-destroy:
          requires:
            - run-inspec-tests
