# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0
name: hashicorp/hashicat-azure/secret-expiration
on: workflow_dispatch
jobs:
  this-is-so-stupid:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is so stupid"
